### ISSUE TITLE
product-list.component.html

### ISSUE THREAD

**Issue by VZhyrytskiy** [olesyk/Shop#2]
ProductComponent генерит аутпут, но в разметке его нет
<div>
  <app-product
    *ngFor="let product of products"
    [item]="product">
  </app-product>
</div>
и не должно быть?

**Comment by olesyk** [comment]
This output is used only for top product, not for product items in the products list. In the task2 it is used for products list as well.
<div class="top_product">
    <h2>Top product: </h2>
    <app-product [item]="topProduct"
                 [isTop]="true"
                 (addProductToCart)="onAddProductToCart($event)"></app-product>
  </div>
